#
#
#
#  YOU NEED TO CLEAR .gitigore to made changes
#


# SITE CONFIGURATION
baseurl: ""
url: "https://elybin.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: khakim assidiqi
  avatar: assets/img/ava-min.jpg
  favicon: assets/img/rsz_inf-min.png
  gravatar: # Email MD5 hash
  description: "a website written by wizard" # used by search engines

  # Header and footer text
  header_text: >
     <p>a website written by wizard.</p>
  header_text_feature_image:
  footer_text: >
   this ugly blog powered by <a href="https://jekyllrb.com/">jekyll</a>.

  # Icons
  rss: false
  email_address: 
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr: 
  gitlab:
  gitter:
  google_plus:
  instagram: "claymachine"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud: "claymachine"
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "@clay_machine"
  wordpress:
  youtube: "UCczaCELSgivYMxrmnU9DVeA"
  github: "elybin"

  # Scripts
  google_analytics: "UA-113947180-1"
  disqus_shortname: "elybin"
  fb_appid: "285677132447016"
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "follow on"
  str_rss_follow: "follow RSS feed"
  str_email: "email"
  str_next_post: "next post"
  str_previous_post: "prev post"
  str_next_page: "next"
  str_previous_page: "prev"
  str_continue_reading: "continue reading"
  str_javascript_required_disqus: "please enable JavaScript to view comments."
  str_search_no_results: "no results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
# keep_files: [app, skripsi-clarita, demo-deriberatif]
exclude: [Gemfile, Gemfile.lock, README.md ]


# deployment
host: 0.0.0.0
port: 4000